= ag-script(1) =

== NAME ==
ag-script - execute component script.

== SYNOPSIS ==
[verse]
'ag <script>' [-n | --dry-run] [<component1> <component2> ...]

[verse]
'ag <script>' [-n | --dry-run] up [-t <component>]

[verse]
'ag <script>' [-n | --dry-run] down [-t <component>]

[verse]
'ag <script>' [-n | --dry-run] all

== DESCRIPTION ==
Executes component scripts. Supported scripts:

build::
    Builds components.

clean::
    Cleans components.

test::
    Runs tests for components. 

Supported usage forms (using 'build' script as an example here, but it works for all other scripts as well):

`ag build`::
    Builds current component or all the specified components. Components are specified by their names or aliases.

`ag build up`::
    Performs upstream build for the current component, i.e. builds all components this component depends on (directly or indirectly), then builds this component.

`ag build down`::
    Performs downstream build for the current component, i.e. builds this component, then builds all components, which are directly or indirectly depend on this component.

`ag build all`::
    Builds all components.

== OPTIONS ==

Using 'build' script as an example here, but it works for all other scripts as well. 

-n::
--dry-run::
    Don't do actual build, just print component names to be built.

-t::
--to::
    Terminator for upstream/downstream builds. Do not build components above the specified component for upstream build. Do not build components below the specified component for downstream build. 

== EXAMPLES ==

Using 'build' script as an example here, but it works for all other scripts as well. 

Build current component:

--------------------------------------------------------------
    ag build    
--------------------------------------------------------------

Build some components:

--------------------------------------------------------------
    ag build comp_name1 comp_alias2 comp_name3
--------------------------------------------------------------

Build all dependencies of this component until comp1 (inclusive), then build this component:

--------------------------------------------------------------
    ag build up -t comp1
--------------------------------------------------------------
